pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/PKarunakar2205/Wipro-Training_SDET.git'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean test'
            }
        }
    }
}