pipeline {

    agent any

    stages {

        stage('Build') {

            steps {

                dir('CapstoneProject') {

                    bat 'mvn clean test'
                }
            }
        }
    }
}
